### ISSUE TITLE
Installation instructions don't lead to a working system

### ISSUE THREAD

**Issue by Stwissel** [fengmk2/nodeblog#7]
Followed the instructions, but then ran into the following issues:

a) there is no server.js, only a app.js
b) connect-render is missing from the list of npm module
c) On Ubuntu 12.04 the lib-expat install is broken. You need to install the dev library first
    sudo apt-get install libexpat1-dev
d) When running node app.js  it terminates with error:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: tqq api not exists
    at Object.init (nodeblog/node_modules/weibo/lib/tapi.js:48:13)

 at Object.<anonymous> (/home/stw/github/nodeblog/controllers/user.js:64:15)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (nodeblog/app.js:10:12)
    at Module._compile (module.js:441:26)

What can I do to make it run?

**Comment by Stwissel** [comment]
Anything I can do?

**Comment by jackywang** [comment]
same questions, How can I do to make it run?
